[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 1
[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 2
[[main]]
  identifier = "memo"
  name = "Memo"
  url = "memo"
  weight = 3
